### ISSUE TITLE
Desktop UX Improvements: Settings Page

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#400]
This ticket is one of three improvement tickets planned for Desktop user experience.

- [x] 1. Basics -- PR #423
- [x] 2. Clicking a server -- PR #425 
- [x] 3. Clicking on “Add new server” opens a dialog -- PR #415
- [x] 4. Clicking on “Edit” opens the same dialog from part 3 -- PR #415
- [x] 5. Clicking on “Remove” opens a dialog to confirm that the user wants to remove the server -- PR #421

----

### PART 1 - Basics

 Core aspects of the current settings page should remain unchanged, apart from minor string changes:
 - Title: Settings
 - **Section 1**: Server Management
   - Displays the Name and URL
   - "Add new server" option
   - "Edit" and "Remove" options
 - **Section 2**: App Options
   - “Cancel” and “Save” buttons hovering over the page
   - “X” on top right corner, which closes the settings page and directs the user to the first server tab, if applicable. If the user has not added a server, the settings page should remain open

![image](https://cloud.githubusercontent.com/assets/13119842/21290256/63be111c-c481-11e6-8f2a-3dae75719216.png)

The following includes improvements to the Settings page:

### PART 2 - Clicking a server

When you click one of the servers under “Server Management”, the Settings page closes and the tab corresponding to that server opens.

### PART 3 - Clicking on “Add new server” opens a dialog

**DIALOG**:
- Title: Add Server
- Input Field 1:
  - Title: Server Display Name
  - Placeholder Text: Server Name
  - Help Text: The name of the server displayed on your desktop app tab bar. 
- Input Field 2:
  - Title: Server URL
  - Placeholder Text: https://example.com
  - Help Text: The URL of your Mattermost server. Must start with http:// or https://.
- Dialog options: 
  - Cancel → Closes the dialog without saving changes
  - Save → Adds server to the end of the Server Management list

**ERROR MESSAGES**:
- If no name is provided, show text “Name is required.”
- If no URL is provided, show text “URL is required.”
- If URL is provided but is missing http:// or https://, show text “URL should start with http:// or https://.”

![image](https://cloud.githubusercontent.com/assets/13119842/21290323/e9753e3c-c483-11e6-8786-c974cc5faa95.png)

**LOCATION:**

The dialog should ideally be located somewhere in the top middle part of the currently active window. Currently, the dialog would always open in the top left corner of the screen, which might be very different from the actual location of the window and therefore not ideal.

If this is difficult to implement or requires a lot of work, alternative options are open.

### PART 4 - Clicking on “Edit” opens the same dialog from part 3, except:
  - fields are pre-populated with the previously specified server display name and server URL
  - title is "Edit Server" instead of "Add Server"

### PART 5 - Clicking on “Remove” opens a dialog to confirm that the user wants to remove the server.

- Title: Remove Server
- Description: This will remove the server from your Desktop App but will not delete any of its data - you can add the server back to the app at any time. \n\n Confirm you wish to remove the [SERVER DISPLAY NAME] server?
- Dialog options: 
  - Cancel → Closes the dialog with no action
  - Remove →  Removes the server from the Server Management section

![image](https://cloud.githubusercontent.com/assets/13119842/21290338/4bdbb4de-c484-11e6-85e3-4a6a72107a5a.png)

----

Note that "team management" in the desktop app will change to "server management" once [team sidebar PR on the platform repo is merged](https://github.com/mattermost/platform/pull/4569
), which adds an additional layer on the left hand sidebar for team management

![image](https://cloud.githubusercontent.com/assets/13119842/21290644/97b60448-c490-11e6-92a9-3ea97857d059.png)

----

Future improvements:

Auto-save app options on the Settings page
  - Removes the need for Cancel/Save buttons
  - More forgiving as a user might leave the page with unsaved changes (and there isn't an easy way to gracefully handle it without opening a separate "discard changes" dialog on the app)

Use a splash screen when a user first installs the app and hasn’t added any servers. This helps improve the onboarding experience with better aesthetic appeal

**Comment by jasonblais** [comment]
Tested on Windows 10, with various different combinations and it looks great. Thank you @yuya-oc! 

Ready to merge,

**Comment by jasonblais** [comment]
PS: I'll no longer accidentally remove a server from the app, yay! :D

**Comment by yuya-oc** [comment]
I added the checklist.

**Comment by jasonblais** [comment]
Closed by #415, #421, #423 and #425. Thanks @yuya-oc and @jnugh!
