### ISSUE TITLE
Desktop UX Improvements: Managing servers

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#401]
This ticket is one of three improvement tickets planned for Desktop user experience.

- [x] Navigation bar -- PR #415
- [x] Adding a new server from the “+” icon -- PR #415
- [x] Opening an app with no servers in Settings page -- PR #435

----

### PART 1 - Navigation bar: 

The navigation bar will display on top of the app itself similar to browser tabs and will have the server display name as specified on the Settings page.

This bar will be hidden if there is just one server specified on the Settings page.

The UI screen below shows:
 - two servers, the first and active server is “Pre-release” and the second is “Bladekick”
 - a “+” button beside the second tab which can be used to add a new server

![image](https://cloud.githubusercontent.com/assets/13119842/21290354/c4869516-c484-11e6-9314-64a488708a40.png)

### PART 2 - Adding a new server from the “+” icon

If a user clicks on the “+” icon, they can enter the name and URL similar to the Settings page. The dialog should be the same from #400, PART 3

![image](https://cloud.githubusercontent.com/assets/13119842/21290364/52baa08e-c485-11e6-8770-bc96c631111d.png)

After clicking “Add”, the new server will appear on the right-most tab of the navigation bar, and the sign in page will be displayed to the user.

### PART 3 - Opening an app with no servers in Settings page

If a user has no servers on the Settings page, a dialog will automatically appear asking them to add a server. The dialog is the same from PART 2 in this ticket (and from #400, PART 3)

Once done, the server is added to the Server Management section.

Note: This also covers the case when a user starts the app for the first time.

---- 

Note that "team management" in the desktop app will change to "server management" once [team sidebar PR on the platform repo is merged](https://github.com/mattermost/platform/pull/4569
), which adds an additional layer on the left hand sidebar for team management

![image](https://cloud.githubusercontent.com/assets/13119842/21290644/97b60448-c490-11e6-92a9-3ea97857d059.png)

----

Future improvements:

Allow users to reorder servers directly on the Server Management page and on the navigation bar. https://mattermost.uservoice.com/forums/306457-general/suggestions/15771343-allow-reordering-teams-in-desktop-application

**Comment by jasonblais** [comment]
Closed via #415 and #435, thanks all!
