### ISSUE TITLE
Incorrect task and publisher name in Windows 10 startup task list

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#542]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

From @lvictorino at https://github.com/mattermost/platform/issues/6493

When Mattermost App is set to be launched at startup, the task manager displays an incorrect name or publisher name that can be very confusing for users.

#### Steps to reproduce

1. Set Mattermost Windows App to start with Windows.
2. Launch Windows Task Manager (CTRL+ALT+SUPRR)
3. Select Startup Tab
4. Mattermost App is under a group named Update(X) and the Publisher is GitHub

![capture2](https://cloud.githubusercontent.com/assets/18822/26450271/de5ee4bc-4156-11e7-9b11-f2e2ff5fe3d9.PNG)

#### Expected behavior
Instead of Update the name of the process should be Mattermost (about the publisher name I don't know how you guys deal with it, but I would expect Mattermost in there too).

**Comment by jasonblais** [comment]
@yuya-oc Is this something that should be fixed by the build process or here in the desktop repo?

**Comment by yuya-oc** [comment]
For `Mattermost` processes, I think we can fix by modifying electron-builder config. However I'm not sure about `Update`.

**Comment by jasonblais** [comment]
Sounds good, I'll assign this to a future milestone and we can investigate more then (since it's only in the Startup tab)

**Comment by jasonblais** [comment]
@yuya-oc I've noticed a few other places where we're referring to "Yuya" instead of Mattermost

1. Mac: Help > About Mattermost
2. Windows 10: Settings > Apps and Features > Mattermost > "Yuya Ochiai" 
![image](https://user-images.githubusercontent.com/13119842/27593564-7af914b8-5b25-11e7-92af-694355d76f9e.png)
3. Copyright notice in [LICENSE.txt](https://github.com/mattermost/desktop/blob/master/LICENSE.txt) refers to Yuya instead of Mattermost.

I'll re-assign this to the next fix version, as I worry it makes the app seem lower quality if it's attributed to an individual rather than an organization.

**Comment by yuya-oc** [comment]
@jasonblais To solve the original problem, we need to set "author" of `src/package.json` with "Mattermost, Inc. \<EMAIL\>". And, for .deb packages, an email address is necessary. Which address should we use?

For LICENCE.txt, I'm not sure how we should write in this case. Would you ask Ian or others? (He had proposed Apache-2.0)

**Comment by jasonblais** [comment]
Sure thing, I'll ask him about it next week (he's travelling today), and also ask about the email address.

What is the email address for? Is it for sending feedback/reports?

**Comment by yuya-oc** [comment]
Probably. On Ubuntu 16.04, "GDebi Package Installer" shows info below.

<img width="328" alt="gdebi" src="https://user-images.githubusercontent.com/1412057/27736926-2e71289c-5de1-11e7-8425-8e2ab7f14029.png">

And after installation, `apt-cache show mattermost-desktop` shows following outputs.

```
Package: mattermost-desktop
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 163445
Maintainer: Yuya Ochiai <yuya0321@gmail.com>
Architecture: amd64
Version: 3.7.0
Depends: gconf2, gconf-service, libnotify4, libappindicator1, libxtst6, libnss3, libxss1
Description: Mattermost
  Mattermost
Description-md5: 05ddf319e2649b9c154b1ad6cb9fcbb8
License: Apache-2.0
Vendor: Yuya Ochiai <yuya0321@gmail.com>
Homepage: https://about.mattermost.com
```

**Comment by jasonblais** [comment]
Got it -- thanks for the info, very useful! I'll follow up on this next week

**Comment by jasonblais** [comment]
@yuya-oc 

1) We can use `feedback@mattermost.com` as the email address on Debian.

2) The copyright at the top of LICENSE.txt can read

```
// Copyright (c) 2015-2016 Yuya Ochiai
// Modified work: Copyright (c) 2016-present Mattermost, Inc. All Rights Reserved.
```

^2016 is when the repo was moved to Mattermost (and you became core committer)

**Comment by jasonblais** [comment]
Closing as most of the issues from this thread are resolved.

Opened a separate issue for tracking remaining things things here: https://github.com/mattermost/desktop/issues/559
